Add and implement Sentry
svthalia/thadmin pull request #31
Opened 2021-05-11 12:22 UTC by Luca-Castelnuovo

Fix #9

2021-05-11 12:32 UTC, JobDoesburg commented on src/main.ts
> +Sentry.init({
Are you sure that this should be added here, and not in App.vue? (I'm not sure, the documentation says "Passing in `Vue` is optional, but if you do not pass it `window.Vue` must be present." and I'm in doubt whether `window.Vue` is present here)

2021-05-11 12:33 UTC, JobDoesburg requested changes

2021-05-11 12:33 UTC, JobDoesburg commented on src/main.ts
> +    "https://d982883f74014ba7a7243ffaa59a3ec0@o263149.ingest.sentry.io/5757558",
Can this be an (environment or repository) secret?

2021-05-11 16:58 UTC, se-bastiaan commented on src/App.vue
> +}
This should obviously not end up in master :p

2021-05-11 17:08 UTC, se-bastiaan requested changes
I think the variables for Sentry can just be `SENTRY_ENVIRONMENT` and `SENTRY_RELEASE` next to `SENTRY_DSN` to the GitHub Actions configuration. The SENTRY_RELEASE environment can be set directly to `environment.GITHUB_SHA` and the prefix `VUE_APP` is not necessary since the Sentry package will grab those.

Unless we want to have the same prefix for all variables, in that case they have to be set on the options as well.

2021-05-12 08:47 UTC, Luca-Castelnuovo commented
> Unless we want to have the same prefix for all variables, in that case they have to be set on the options as well.

And do we?

2021-05-12 08:52 UTC, se-bastiaan commented
> 
> 
> > Unless we want to have the same prefix for all variables, in that case they have to be set on the options as well.
> 
> And do we?

Good point, I don't really mind having the Sentry variables separate. But I know how Sentry works. And it makes them less visible for new maintainers of this repository that have not read the Sentry docs.

So for transparency I would add them separate probably.

2021-05-12 08:58 UTC, Luca-Castelnuovo commented
> I assume the secret should also be added in here: [`master`/.github/workflows/terraform.yml](https://github.com/svthalia/thadmin/blob/master/.github/workflows/terraform.yml)
> 
> (so add the secret in the repository settings, then edit the terraform workflow to extract the secret and use it as environment variable)

I don't have access to repo settings

2021-05-12 09:18 UTC, Luca-Castelnuovo commented
> I think the variables for Sentry can just be `SENTRY_ENVIRONMENT` and `SENTRY_RELEASE` next to `SENTRY_DSN` to the GitHub Actions configuration. The SENTRY_RELEASE environment can be set directly to `environment.GITHUB_SHA` and the prefix `VUE_APP` is not necessary since the Sentry package will grab those.
> 
> Unless we want to have the same prefix for all variables, in that case they have to be set on the options as well.

https://cli.vuejs.org/guide/mode-and-env.html#:~:text=Note%20that%20only%20NODE_ENV%2C%20BASE_URL%2C%20and%20variables%20that%20start%20with%20VUE_APP_%20will%20be%20statically%20embedded%20into%20the%20client%20bundle%20with%20webpack.DefinePlugin.%20It%20is%20to%20avoid%20accidentally%20exposing%20a%20private%20key%20on%20the%20machine%20that%20could%20have%20the%20same%20name.

Note that only NODE_ENV, BASE_URL, and variables that start with VUE_APP_ will be statically embedded into the client bundle with webpack.DefinePlugin. It is to avoid accidentally exposing a private key on the machine that could have the same name.

2021-05-12 10:37 UTC, se-bastiaan approved these changes
Should have permissions now

2021-05-12 10:38 UTC, Luca-Castelnuovo commented
![Screen Shot 2021-05-12 at 12 38 05 PM](https://user-images.githubusercontent.com/26206253/117961906-ee19ef80-b31e-11eb-808e-ef43201c1f07.png)

@se-bastiaan, not yet I think.

2021-05-12 10:45 UTC, Luca-Castelnuovo commented
**TODO:** add github actions secret

2021-05-12 11:55 UTC, Luca-Castelnuovo commented
I saw that the secret has been created.

2021-05-18 11:25 UTC, JobDoesburg approved these changes

2021-05-18 11:25 UTC, merged

2021-05-18 11:25 UTC, JobDoesburg commented
Let's see if this works